/* autogenerated: flow handler */
#include "ir2ael_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

Ir2AelStatus ir2ael_flow_handle_loop_ctrl(Ir2AelState *s, size_t *idx, const IRInst *inst) {
    if (!s || !inst || !idx) return IR2AEL_STATUS_FAIL;
    Ir2AelState *st = s;
    const IRProgram *program = s->program;
    AelEmitter *out = s->out;
    char *err = s->err;
    size_t err_cap = s->err_cap;
    size_t i = *idx;

#define RETURN_STATUS(_status) do { *idx = i; return (_status); } while (0)

    if (inst->op == OP_LOOP_AGAIN || inst->op == OP_LOOP_EXIT) {
        do {
                /* Break/continue are emitted via OP_BRANCH_TRUE patterns; ignore here. */
                continue;
        } while (0);
        RETURN_STATUS(IR2AEL_STATUS_HANDLED);
    }

    /* Control-flow labels/branches: handle if/else templates, otherwise ignore. */
    RETURN_STATUS(IR2AEL_STATUS_NOT_HANDLED);
#undef RETURN_STATUS
}
